export class DatosSingleton {
  usuario: string;
  tipoUsuario: string;
  labelPrimerNombre: string;
  labelSegundoNombre: string;
  labelPrimerApellido: string;
  labelSegundoApellido: string;
  labeledad: string;
  labelNoDocumento: string;
  labelTipoDocumento: string;
  labelGenero: string;
  labelFechaNacimiento: string;
  labelLugarDeNacimiento: string;
  labelEstadoCivil: string;
  labelEscolaridad: string;
  labelCargoDependencia: string;
  labelDireccionCasa: string;
  labelTelefono: string;
  labelAseguradora: string;
  labelAFP: string;
  labelARL: string;
  menuOcupacionalDatosPrincipales:string;
  menuOcupacionalHistoriaLaboral: string;
  menusubmenuOcupacionalHistoriaLTrabajoAC: string;
  labelNombreEmpresa: string;
	labelActividadEconomica: string;
	labelFechaIngreso: string;
	labelAntiguo: string;
	labelCargo: string;
	labelDescripcionTareasFuncion: string;
  menusubmenuOcupacionalHistoriaLTrabajoPre: string;
	tablaTrabajoPreLabelEmpresa: string;
	tablaTrabajoPreLabelCargOficina: string;
	tablaTrabajoPreLabelTimepo: string;
	menusubmenuOcupacionalHistoriaLAntecedentesTrabajo: string;
}
