import { TipoDocumento } from './tipoDocumento';
import { Ciudad } from './ciudad';
import { Aseguradora } from './aseguradora';
import { Localidad } from './localidad';
import { Historias } from './historias';
export class Persona {
  seqPersona: number;
  nomPrimerNombre: string;
  nomPrimerApellido: string;
  nomSegundoNombre: string;
  nomSegundoApellido: string;
  tipoDocumento: TipoDocumento;
  numeroDocumento: string;
  edad: number;
  direccion: string;
  telefono: string;
  correo: string;
  celular: string;
  fechaCreacion: Date;
  genero: string;
  estadoCivil: string;
  fechaNacimiento: string;
  lugarNacimiento: Ciudad;
  barrio: string;
  lugarDeResidencia: Ciudad;
  escolaridad: string;
  nomCargoDep: string;
  AFP: string;
  ARL: string;
  grupoSanguineo: string;
  RH: string;
  telEmergencia: string;
  nomEmergencia: string;
  parentescoEmergencia: string;
  aseguradora: Aseguradora;
  localidad: Localidad;
  historias: Historias[];
  rolUsuario: string;
  constructor() {
    this.seqPersona = null;
    this.nomPrimerNombre= null;
    this.nomPrimerApellido= null;
    this.nomSegundoNombre= null;
    this.nomSegundoApellido= null;
    this.tipoDocumento= new TipoDocumento();
    this.numeroDocumento= null;
    this.edad = null;
    this.direccion= null;
    this.telefono= null;
    this.correo= null;
    this.celular= null;
    this.fechaCreacion= new Date();
    this.genero= null;
    this.estadoCivil= null;
    this.fechaNacimiento= null;
    this.lugarNacimiento= new Ciudad();
    this.barrio= null;
    this.lugarDeResidencia= new Ciudad();
    this.escolaridad= null;
    this.nomCargoDep= null;
    this. AFP= null;
    this.ARL= null;
    this.grupoSanguineo= null;
    this.RH= null;
    this.telEmergencia= null;
    this.nomEmergencia= null;
    this.parentescoEmergencia= null;
    this.aseguradora= new Aseguradora();
    this.localidad= new Localidad();
    this.rolUsuario= null;
    this.historias = new Array<Historias>();
  }
}
